project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

website: 
    
  description: "Practical guides for accessing, analyzing, and visualizing GRID3 data"
  site-url: https://<your-org>.github.io/<your-repo>/
  repo-url: https://github.com/<your-org>/<your-repo>
  repo-actions: [edit, issue]

  navbar:
    logo: https://grid3.org/content/themes/grid3/img/logos/GRID3_FullColor.png

     

    left:
      - text: "Home"
        href: index.qmd

      - text: "Data Access" 
        menu:
          - text: "Notebook 1" 
            href: notebooks/nb1.ipynb

          - text: "User Guide Template"
            href: notebooks/ures_guide_template.Rmd

      - text: "Analysis"
        menu:      
          - text: "Analysis 1"
            href: notebooks/ures_guide_template.Rmd
      - text: "Visualization"
        menu:
          - text: "Visualization 1"
            href: notebooks/visualization.ipynb
       


    right:
      - icon: github
        href: https://github.com/<your-org>/<your-repo>
      - icon: twitter
        href: https://twitter.com/grid3_org
      - icon: linkedin
        href: https://www.linkedin.com/company/grid3-org/
      - icon: facebook
        href: https://www.facebook.com/grid3org/
      - icon: youtube
        href: https://www.youtube.com/@grid3org
      - icon: globe
        href: https://grid3.org



  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd

      - section: "Data Access"
        contents:
          - notebooks/nb1.ipynb
          # - notebooks/query-feature-services.ipynb
          # - notebooks/catalog-metadata.ipynb

      - section: "Visualization"
        contents:
          # - notebooks/folium-maps.ipynb
          # - notebooks/geopandas-plots.ipynb

      - section: "Reference"
        contents:
          # - notebooks/api-reference.ipynb



format:
  html:
    theme: default
    css: custom.css
    toc: true
    toc-location: right
    toc-depth: 4
    smooth-scroll: true
    code-copy: true
    number-sections: true
    fig-width: 800
    fig-height: 600
    fig-alt-text: true
    lightbox: true
    navbar:
      type: default
    sidebar:
      collapse-level: 2
      float: false
      width: 300px 
    favicon: https://grid3.org/content/themes/grid3/img/logos/favicon.ico 
      

         