project:
  type: website
  output-dir: docs 
  render:   
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "!notebooks/colab/"



execute:
  #enabled: false
  freeze: auto
  echo: true
  warning: false
  message: false
  

website: 
    
  description: "Practical guides for accessing, analyzing, and visualizing GRID3 data"
  site-url: https://ciesin.github.io/GRID3_dataUserGuide/
  repo-url: https://github.com/ciesin/GRID3_dataUserGuide
  repo-actions: [edit, issue]

  

  navbar:
    logo: https://grid3.org/content/themes/grid3/img/logos/GRID3_FullColor.png

     

    left:
      - text: "Home"
        href: index.qmd

      - text: "Data Access" 
        menu:

          - text: "User Guide Template"
            href: notebooks/user_guide_template.qmd
          - text: "Friction Surface by LGA"
            href: notebooks/accessing_friction_surface_by_lga.qmd

      - text: "Analysis"
        menu:      
          - text: "GRID3 Nigeria Road Network Analysis"
            href: notebooks/api_nga_network.ipynb
      - text: "Visualization"
        menu:
          - text: "Visualization 1"
             
       


    right:
      - icon: github
        href: https://github.com/<your-org>/<your-repo>
      - icon: twitter
        href: https://twitter.com/grid3_org
      - icon: linkedin
        href: https://www.linkedin.com/company/grid3-org/
      - icon: facebook
        href: https://www.facebook.com/grid3org/
      - icon: youtube
        href: https://www.youtube.com/@grid3org
      - icon: globe
        href: https://grid3.org



  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd

      - section: "Data Access"
        contents: 
          - notebooks/user_guide_template.qmd
          - notebooks/accessing_friction_surface_by_lga.qmd

      - section: "Analysis"
        contents:
          - notebooks/api_nga_network.ipynb 
          # - notebooks/folium-maps.ipynb
          # - notebooks/geopandas-plots.ipynb

      - section: "Visualization"
        contents:
          # - notebooks/api-reference.ipynb

  google-analytics: 
    tracking-id: "G-45WWDMVLWW"
    anonymize-ip: true



format:
  html:
    theme: default
    css: custom.css
    toc: true
    toc-location: right
    toc-depth: 4
    smooth-scroll: true
    code-copy: true
    number-sections: true
    fig-width: 6
    fig-height: 4
    fig-dpi: 120
    fig-alt-text: true
    lightbox: true
    navbar:
      type: default
    sidebar:
      collapse-level: 2
      float: false
      width: 300px 
    favicon: https://grid3.org/content/themes/grid3/img/logos/favicon.ico 
    include-in-header: google-analytics.html
    footer: |
      **(c) 2026 CIESIN - Center for International Earth Science Information Network (CIESIN), Columbia University.** <br>
      [info@ciesin.columbia.edu](mailto:info@ciesin.columbia.edu) | [ciesin.columbia.edu](https://ciesin.columbia.edu) | [grid3.org](https://grid3.org)

      



         